
# Copyright 2022 EngFlow Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("defs.bzl", "remote_go_toolchain", "remote_go_bootstrap_toolchain")
load("@prelude//toolchains:cxx.bzl", "cxx_tools_info_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")
load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")

# Python toolchain used in scripts that bootstrap other aspects of the Buck2 prelude.
system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

remote_go_bootstrap_toolchain(
    name = "go_bootstrap",
    visibility = ["PUBLIC"],
)

# c++ toolchain required implicitly for py targets.
cxx_tools_info_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

remote_go_toolchain(
    name = "go",
    visibility = ["PUBLIC"],
)

# Default toolchain for remote execution of tests.
# Note it defines a profile with a capability that defines the `container-image` that matches the one defined in //platforms:remote_platform. 
# Capabilities are passed to the RE service to find workers that match them as Platform options.
remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
    default_profile = "cxx_re_toolchain",
    profiles = {
        "cxx_re_toolchain": {
            "use_case": "cxx-testing",
            "capabilities": {
                "container-image" : "docker://public.ecr.aws/docker/library/golang:1.23.3-bookworm@sha256:3f3b9daa3de608f3e869cd2ff8baf21555cf0fca9fd34251b8f340f9b7c30ec5",
            },
        }
    },
)

# In some cases the execution of test can fail looking for this `noop_test_toolchain`.
noop_test_toolchain(
    name = "test",
    visibility = ["PUBLIC"],
)
