name: Renovate Dependency Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1" # Run every monday at midday

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Renovate Update
        uses: renovatebot/github-action@v34.146.1
        env:
        with:
          configurationFile: renovate.json
          token: ${{ secrets.ANDRES_REENOVATE_TOKEN }}
