java_library(
    name = "writer",
    srcs = ["Writer.java"],
    visibility = ["//visibility:public"],
)

java_test(
    name = "writer_test",
    srcs = ["WriterTest.java"],
    test_class = "com.engflow.varyinginputs.writer.WriterTest",
    deps = [
        ":writer",
    ],
)
