package(default_visibility = ["//visibility:public"])

platform(
    name = "macos_arm64",
    constraint_values = [
        "@platforms//os:macos",
        "@platforms//cpu:arm64",
        "@io_bazel_rules_go//go/toolchain:cgo_off",
        "@io_bazel_rules_dotnet//dotnet/toolchain:6.0.101",
    ],
)
