load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "bazel_toolchains",
    commit = "cb0929a385a058d1839db410e0aca4d23e3543df",  # Release 3.7.1
    remote = "https://github.com/bazelbuild/bazel-toolchains.git",
)

load("@bazel_toolchains//rules:rbe_repo.bzl", "rbe_autoconfig")

rbe_autoconfig(
    name = "engflow_remote_config",
    detect_java_home = True,
    digest = "sha256:7a4f71955cb0f74ace1e285314933a8c9608f7b20e720abc10cb8107b7093b19",
    registry = "gcr.io",
    repository = "bazel-public/ubuntu2004-java11",
)
