load("@rules_swift//swift:swift.bzl", "swift_test")

swift_test(
    name = "swift_test",
    size = "small",
    srcs = [
        "example.swift",
        "main.swift",
    ],
    tags = [
        "manual",
        "no-ci",  # Broken toolchain setup
    ],
)
