load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "main",
    srcs = ["Main.java"],
    deps = [
        "//java/com/engflow/internship/cycleexample/class_a",
        "//java/com/engflow/internship/cycleexample/class_b",
        "//java/com/engflow/internship/cycleexample/class_c",
    ],
    main_class = "com.engflow.internship.cycleexample.main.Main",
)