# Copyright 2022 EngFlow Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

rust_library(
    name = "library",
    srcs = glob(
        ["src/**/*.rs"],
    ),
)

rust_binary(
    name = "main",
    srcs = glob(
        ["bin/**/*.rs"],
    ),    
    crate_root = "bin/main.rs",
    deps = [":library"],
)

rust_test(
    name = "test",
    srcs = glob(
        ["test/**/*.rs"],
    ),
    deps = [":library"],
    # TODO: remove these once https://github.com/facebook/buck2/pull/826 gets merged.
    remote_execution_action_key_providers = select({
        "//platforms:engflow": "//platforms:remote_execution_action_keys",
        "DEFAULT": None,
    }),
)
