java_library(
    name = "reader",
    srcs = ["Reader.java"],
    visibility = ["//visibility:public"],
)

java_test(
    name = "reader_test",
    srcs = ["ReaderTest.java"],
    test_class = "com.engflow.varyinginputs.reader.ReaderTest",
    deps = [
        ":reader",
    ],
)
