name: CI

on:
  push:
    branches: [ main ]
    tags: 'v*'
  pull_request:
    branches: [ main ]

# Recommended here: https://github.com/bazelbuild/bazelisk/issues/88#issuecomment-625178467
env:
  BAZELISK_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]
    steps:
    - uses: actions/checkout@v2
    - name: build everything
      run: bazel build //...

