name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

# Cancel pending jobs on push.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run
concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

# Recommended here: https://github.com/bazelbuild/bazelisk/issues/88#issuecomment-625178467
env:
  BAZELISK_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OPAL_RPC_CREDENTIALS: ${{ secrets.OPAL_RPC_CREDENTIALS }}

jobs:
  test-matrix:
    runs-on:
      - self-hosted
      - "os=${{ matrix.os }}"
      - "arch=${{ matrix.arch }}"
      - "os_distribution=${{ matrix.os_distribution }}"
      - "os_version=${{ matrix.os_version }}"
      - "revision=${{ matrix.revision }}"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: x64
            os_distribution: debian
            os_version: 11
            revision: 9d1b5ce956bea2e76b0bc4525ed6c59b5777f4bc
            remote_execution: 'false'

          - os: linux
            arch: x64
            os_distribution: debian
            os_version: 11
            revision: 9d1b5ce956bea2e76b0bc4525ed6c59b5777f4bc
            remote_execution: 'true'

          - os: macos
            arch: x64
            os_distribution: monterey
            os_version: "12"
            revision: 9d1b5ce956bea2e76b0bc4525ed6c59b5777f4bc
            remote_execution: 'false'

          - os: macos
            arch: x64
            os_distribution: monterey
            os_version: "12"
            revision: 9d1b5ce956bea2e76b0bc4525ed6c59b5777f4bc
            remote_execution: 'true'

    steps:
      - uses: actions/checkout@v3

      - name: Set up authentication
        shell: bash
        run: cp infra/bazelrc .bazelrc.user

      - name: Generate python requirements lock
        shell: bash
        run: bazel run //python:requirements.update

      - name: Build and test
        env:
          ARCH: ${{ matrix.arch }}
          OS: ${{ matrix.os }}
          REMOTE_EXECUTION: ${{ matrix.remote_execution }}
        run: python3 infra/test-all.py
