name: CI

on:
  push:
    branches:
      - "main"
  # TODO(yannic): Remove after merging https://github.com/EngFlow/example/pull/119.
  pull_request:
    branches:
      - "main"
  pull_request_target:
    branches:
      - "main"

# Recommended here: https://github.com/bazelbuild/bazelisk/issues/88#issuecomment-625178467
env:
  BAZELISK_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]
    steps:
      - uses: actions/checkout@v3
      
      - name: Print dummy secret
        run: echo "${{ secrets.DUMMY_SECRET }}" | base64
