name: Renovate Dependency Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 1,15 * *" # Run 1st and 15th of the month

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Renovate Update
        uses: renovatebot/github-action@v34.146.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
