name: Renovate Dependency Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # Run the 1st of each month

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Renovate Update
        uses: renovatebot/github-action@v41.0.6
        with:
          configurationFile: renovate-global.json
          token: ${{ secrets.GITHUB_TOKEN }}
